name: i18n

on:
  push:
    branches: [develop]
    paths:
      - gps/app/locales/en.json
      - gps/app/locales/eula/en.html
      - gps/ios/en.lproj/*.strings
      - gps/android/app/src/main/res/values/strings.xml
      - .github/workflows/*.yml
      - gps/app/locales/*.sh
  pull_request:
    branches: [develop]
    paths:
      - gps/app/locales/en.json
      - gps/app/locales/eula/en.html
      - gps/ios/en.lproj/*.strings
      - gps/android/app/src/main/res/values/strings.xml
      - .github/workflows/*.yml
      - gps/app/locales/*.sh

jobs:
  # Only run on a final merge into develop, uploads all changed keys to Lokalised
  lokalise-upload:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: upload english files
        run: yarn i18n:push
        env:
          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}

  # Run on PRs, checks for any added keys that are missing in the gps/app/locales/en.json file
  check-i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: cached node_modules/
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - run: yarn --frozen-lockfile
        if: steps.cache.outputs.cache-hit != 'true'

      - run: yarn i18n:check
