name: Lint

on:
  pull_request:
    branches:
      - develop
      - release-candidate
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - run: yarn --frozen-lockfile

      # v1 is broken, the given sha was the latest master (but we dont want to track master)
      - uses: tinovyatkin/action-eslint@8b32772f075413f9192f43641e03d9bd0abae621
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint # this is the job name from above 👆
